project:
  type: website

website:
  title: "datathon_winter_2025"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About the Data
      - href: mapview.qmd
        text: R Mapview
      - href: python-spatial.qmd
        text: Python
      - href: datasette.qmd
        text: SQL interface
      - href: questions.qmd
        text: Research Questions

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



